import type { Metadata } from "next";
import { Lexend_Giga } from "next/font/google";
import "./globals.css";

const lexendGiga = Lexend_Giga({
  subsets: ["latin"],
  weight: ["400"],
  display: "swap",
  variable: "--font-lexend-giga",
});

export const metadata: Metadata = {
  title: "Miu Petshop",
  description: "Generated by firman",
  icons: "/images/oyon.png",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={lexendGiga.className}>
        <div className="min-h-screen max-w-lg mx-auto border overflow-x-hidden scroll-smooth">{children}</div>
      </body>
    </html>
  );
}
