import type { Metadata } from "next";
import { Lexend_Giga } from "next/font/google";
import "./globals.css";
import SessionInitializer from "@/components/SessionInitializer";
import SnapScript from "@/components/SnapScript";
import { Toaster } from "@/components/ui/sonner";

const lexendGiga = Lexend_Giga({
  subsets: ["latin"],
  weight: ["400"],
  display: "swap",
  variable: "--font-lexend-giga",
});

export const metadata: Metadata = {
  title: "Miu Petshop",
  description: "Generated by firman",
  icons: "/images/oyon.png",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${lexendGiga.className}`}>
        <div className="min-h-screen max-w-md mx-auto overflow-x-hidden ">
          <SessionInitializer />
          {children}
          <SnapScript />
          <Toaster richColors closeButton />
        </div>
      </body>
    </html>
  );
}
